### PR TITLE
fix: added validate statements

### LINKED ISSUE #52: Plugin fails starting from Serverless v2.5.0
Serverless just released a new version of the npm package (https://github.com/serverless/serverless/releases/tag/v2.5.0) and the plugin started to fail with following error:
<details>
<summary><code>Error & stack trace</code></summary>

```
Type Error ---------------------------------------------
 
  TypeError: this.awsPackagePlugin.validateStatements is not a function
      at ServerlessIamPerFunctionPlugin.validateStatements (/home/circleci/repo/node_modules/serverless-iam-roles-per-function/dist/lib/index.js:49:31)
      at ServerlessIamPerFunctionPlugin.createRoleForFunction (/home/circleci/repo/node_modules/serverless-iam-roles-per-function/dist/lib/index.js:189:14)
      at ServerlessIamPerFunctionPlugin.createRolesPerFunction (/home/circleci/repo/node_modules/serverless-iam-roles-per-function/dist/lib/index.js:284:18)
      at /snapshot/serverless/lib/classes/PluginManager.js:510:55
  From previous event:
      at PluginManager.invoke (/snapshot/serverless/lib/classes/PluginManager.js:510:22)
      at /snapshot/serverless/lib/classes/PluginManager.js:545:24
  From previous event:
      at PluginManager.run (/snapshot/serverless/lib/classes/PluginManager.js:545:8)
      at /snapshot/serverless/lib/Serverless.js:168:33
  From previous event:
      at Serverless.run (/snapshot/serverless/lib/Serverless.js:155:74)
      at /snapshot/serverless/scripts/serverless.js:50:26
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Object.<anonymous> (/snapshot/serverless/scripts/serverless.js:50:4)
      at Module._compile (pkg/prelude/bootstrap.js:1320:22)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10)
      at Module.load (internal/modules/cjs/loader.js:984:32)
      at Function.Module._load (internal/modules/cjs/loader.js:877:14)
      at Module.require (internal/modules/cjs/loader.js:1024:19)
      at Module.require (pkg/prelude/bootstrap.js:1225:31)
      at require (internal/modules/cjs/helpers.js:72:18)
      at Object.<anonymous> (/snapshot/serverless/bin/serverless.js:47:1)
      at Module._compile (pkg/prelude/bootstrap.js:1320:22)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10)
      at Module.load (internal/modules/cjs/loader.js:984:32)
      at Function.Module._load (internal/modules/cjs/loader.js:877:14)
      at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12)
      at internal/main/run_main_module.js:17:47
```
</details>

I found a PR, which caused this error: https://github.com/serverless/serverless/pull/8297
Basically, the method, which was used to validate the iam statements, was removed from `serverless` package at all, so there should be a different way to validate the statements in order to align with the new versions of `serverless`.

### PR DESCRIPTION
**Pull request by andersquist**
Perhaps not the most elegant of solutions but it will keep this plugin going post version 2.5.0 of Serverless for now I guess. 

Be happy to get any feedback.

Closes #52 .

### CODE REVIEW

**Review by randomhash — APPROVED** [review]

File: src/lib/index.ts [hunk 1]
```diff
@@ -43,23 +43,42 @@ class ServerlessIamPerFunctionPlugin {
...
+      }	
+    }	
+
+    if (violationsFound) {	
+      const errorMessage = [	
+        'iamRoleStatements should be an array of objects,',	
+        ' where each object has Effect, Action / NotAction, Resource / NotResource fields.',	
+        ` Specifically, ${violationsFound}`,	
+      ].join('');	
+      throw new this.serverless.classes.Error(errorMessage);
```
Comment (randomhash) [inline src/lib/index.ts:80]: this better to replace with common error handler that already in package

**Comment by nkeating-mutualofenumclaw** [comment]
Any chance we can get these changes out soon?  A lot of tools are broken with the latest version of serverless

**Comment by andersquist** [comment]
I removed node versions less than 10 in the build matrix since those are versions that Serverless supports these days.

This should now be ready to merge.

**Comment by hawkaa** [comment]
So validation was removed from the original serverless package and now moved in here? Or if it is still in the original serverless package, it changed location?

Also, seems like there is another PR also tackling the issue: https://github.com/functionalone/serverless-iam-roles-per-function/pull/54

**Comment by randomhash** [comment]
@hawkaa it is moved out completely
Looks like it is better PR to proceed with, my has bigger updates.
If sls version will be bumped up here, I will close my or, as useless ;)

**Comment by hawkaa** [comment]
Sounds good.

>  it is moved out completely
If the main package no longer needs validation for the roles and statements, why does this one? It would make sense that they would handle parsing the same way across packages?

**Comment by andersquist** [comment]
I'll bump it to `^1.80.0` because it is the earliest version of `serverless` that doesn't fail the test after inverting the global `DependsOn` check in the tests. Not having the check at all still makes it compatible with version `^1.51.0` afaik and I guess there are still a lot of people out there running older versions...

**Comment by Enase** [comment]
any chance to get it merged and released?

**Comment by jack1902** [comment]
@randomhash any chance this can be published?

**Comment by randomhash** [comment]
@jack1902 
Sorry, but I am not the owner of this package, would love to publish

**Comment by Enase** [comment]
@glicht  Any plans to publish new fixed version?
